image: node:alpine

before_script:
  - yarn install

stages:
  - test
  - dev

test:latest:
  stage: test
  script:
    - yarn test
  tags:
    - docker

test:8:
  image: node:8-alpine
  stage: test
  script:
    - yarn test
  tags:
    - docker

test:6:
  image: node:6-alpine
  stage: test
  script:
    - yarn test
  tags:
    - docker

test:4:
  image: node:4-alpine
  stage: test
  script:
    - yarn test
  tags:
    - docker

update-resources:
  stage: dev
  before_script:
    - yarn global add gulp@^4.0.0 bower
    - yarn install
    - bower install
  script:
    - gulp
    - yarn test
  tags:
    - docker
