image: node:alpine

before_script:
  - yarn install

stages:
  - test
  - dev

test:latest:
  stage: test
  script:
    - yarn test
  tags:
    - docker

test:14:
  image: node:14-alpine
  stage: test
  script:
    - yarn test
  tags:
    - docker

test:12:
  image: node:12-alpine
  stage: test
  script:
    - yarn test
  tags:
    - docker

test:10:
  image: node:10-alpine
  stage: test
  script:
    - yarn test
  tags:
    - docker

update-resources:
  stage: dev
  before_script:
    - yarn global add gulp@^4.0.0 bower
    - yarn install
    - bower install --allow-root
  script:
    - gulp
    - yarn test
  tags:
    - docker
